/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agency;

import java.awt.Color;
import java.util.HashMap;

/**
 *
 * @author Muhammed Ali
 */
public class AddFirms extends javax.swing.JFrame {
    
    Operations op;
    private Color actColor = new Color(187,187,187);
    private HashMap<String,Float> hotelMap;
    private boolean isTicket;
    private float points;
    /**
     * Creates new form AddFirms
     */
    public AddFirms() {
        initComponents();
        op = new Operations();
        isTicket = true;
        init();
    }
    
    private void init(){
        btn_hotels.setBackground(Color.gray);
        
        String[] firms = op.getFirms().toArray(new String[0]);
        selectFirmBox.setModel(new javax.swing.DefaultComboBoxModel<>(firms));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_firms = new javax.swing.JButton();
        btn_hotels = new javax.swing.JButton();
        selectFirmBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pointToUpdate = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firmName = new javax.swing.JTextField();
        pointsToAdd = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_firms.setText("Ulaşım Firmaları");
        btn_firms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firmsActionPerformed(evt);
            }
        });

        btn_hotels.setText("Oteller");
        btn_hotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hotelsActionPerformed(evt);
            }
        });

        selectFirmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firma Seçiniz" }));
        selectFirmBox.setPreferredSize(new java.awt.Dimension(132, 22));
        selectFirmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFirmBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Puan:");

        btn_update.setText("Güncelle");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Yeni Firma Ekle");

        firmName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firmName.setText("Firma Adı");
        firmName.setToolTipText("");
        firmName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firmNameMouseClicked(evt);
            }
        });

        pointsToAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pointsToAdd.setToolTipText("Puan");

        btn_add.setText("Ekle");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel3.setText("Puan:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btn_firms)
                .addGap(18, 18, 18)
                .addComponent(btn_hotels, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(selectFirmBox, 0, 177, Short.MAX_VALUE)
                    .addComponent(firmName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btn_add))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_firms)
                    .addComponent(btn_hotels))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(firmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pointToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update)
                            .addComponent(selectFirmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pointsToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_add)
                        .addComponent(jLabel3)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firmNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firmNameMouseClicked
        firmName.setText("");
    }//GEN-LAST:event_firmNameMouseClicked

    private void selectFirmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFirmBoxActionPerformed
        
        if(isTicket){
            if(selectFirmBox.getSelectedIndex() == 0)
                return;
            String fName = (String) selectFirmBox.getSelectedItem();
            Float point = op.getPoint(fName);
            pointToUpdate.setText(Float.toString(point));
        }else{
            String key = (String) selectFirmBox.getSelectedItem();
            points = hotelMap.get(key);
            pointToUpdate.setText(Float.toString(points));
        }
    }//GEN-LAST:event_selectFirmBoxActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(selectFirmBox.getSelectedIndex()==0)
            return;
        
        if(isTicket){
            String fName = (String) selectFirmBox.getSelectedItem();
            float point = Float.parseFloat(pointToUpdate.getText());
            op.updateFirmPoints(fName,point);
        }else{
            String fName = (String) selectFirmBox.getSelectedItem();
            float point = Float.parseFloat(pointToUpdate.getText());
            op.updateHotelPoints(fName,point);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(firmName.getText().isEmpty() || firmName.getText().matches("Firma Adı") || pointsToAdd.getText().isEmpty())
            return;
        String fName = firmName.getText();
        float point = Float.parseFloat(pointsToAdd.getText());
        
        op.addFirm(fName,point);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_firmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firmsActionPerformed
        btn_hotels.setBackground(Color.gray);
        btn_firms.setBackground(actColor);
        isTicket = true;
        
        String[] firms = op.getFirms().toArray(new String[0]);
        selectFirmBox.setModel(new javax.swing.DefaultComboBoxModel<>(firms));
        
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        firmName.setVisible(true);
        pointsToAdd.setVisible(true);
        btn_add.setVisible(true);
    }//GEN-LAST:event_btn_firmsActionPerformed

    private void btn_hotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hotelsActionPerformed
        btn_firms.setBackground(Color.gray);
        btn_hotels.setBackground(actColor);
        isTicket = false;
        
        hotelMap = op.getHotels();
        String[] hotels = hotelMap.keySet().toArray(new String[0]);
        selectFirmBox.setModel(new javax.swing.DefaultComboBoxModel<>(hotels));
        
        String key = (String) selectFirmBox.getItemAt(0);
        points = hotelMap.get(key);
        pointToUpdate.setText(Float.toString(points));
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        firmName.setVisible(false);
        pointsToAdd.setVisible(false);
        btn_add.setVisible(false);
    }//GEN-LAST:event_btn_hotelsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFirms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFirms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFirms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFirms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFirms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_firms;
    private javax.swing.JButton btn_hotels;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField firmName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pointToUpdate;
    private javax.swing.JTextField pointsToAdd;
    private javax.swing.JComboBox<String> selectFirmBox;
    // End of variables declaration//GEN-END:variables
}
